/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
package ch.plaintext.flyway;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Status report 29.08.2026, measure 13: guardrail covering ALL Flyway migrations of the
 * root reactor ({@code <modul>/src/main/resources/db/migration/V*.sql}).
 *
 * <ul>
 *   <li><b>File name</b> {@code V<epoch>__<beschreibung>.sql} — the number comes from
 *       {@code ./getflywaynr} (Unix seconds), so that modules cannot get in each other's way.</li>
 *   <li><b>Version number unique across the whole reactor.</b> Two modules shipped the very same
 *       {@code V1774038471__create_branding_logo_table.sql} (plaintext-root-flyway and
 *       plaintext-admin-settings, identical content). Flyway only failed to notice because the
 *       classpath scanner collapses equally named resources — a single differing line in one of
 *       the copies would have caused a checksum conflict at startup. The copy in the Flyway
 *       module has been removed; the table belongs to {@code BrandingLogo} in settings.</li>
 *   <li><b>PostgreSQL syntax.</b> The apps only ever run on {@code jdbc:postgresql}; H2/HSQLDB/
 *       MySQL idioms (denylist below) would otherwise only surface at deploy time.</li>
 * </ul>
 *
 * @author info@plaintext.ch
 * @since 2026
 */
@DisplayName("Flyway-Migrationen des Reactors")
class FlywayMigrationenTest {

    private static final Pattern DATEINAME = Pattern.compile("^V(\\d+)__[A-Za-z0-9_]+\\.sql$");

    /** Non-PostgreSQL idioms; {@code IDENTITY} is PostgreSQL only when written as {@code ... AS IDENTITY}. */
    private static final Pattern FREMDE_SYNTAX = Pattern.compile(
            "\\bSET\\s+DATABASE\\b|\\bCREATE\\s+(?:MEMORY|CACHED)\\s+TABLE\\b|\\bLONGVARCHAR\\b"
                    + "|\\bAUTO_INCREMENT\\b|\\bENGINE\\s*=|\\bMODIFY\\s+COLUMN\\b|\\bNVARCHAR\\b"
                    + "|\\bTINYINT\\b|\\bDATETIME\\b|\\bCLOB\\b|\\bBLOB\\b|`|(?<!\\bAS\\s)\\bIDENTITY\\b",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern SQL_KOMMENTAR = Pattern.compile("--[^\\n]*");

    @Test
    void denylistErkenntFremdeSyntaxUndLaesstPostgresDurch() {
        assertTrue(FREMDE_SYNTAX.matcher("id BIGINT AUTO_INCREMENT PRIMARY KEY").find());
        assertTrue(FREMDE_SYNTAX.matcher("id BIGINT IDENTITY PRIMARY KEY").find());
        assertTrue(FREMDE_SYNTAX.matcher("body CLOB").find());
        assertFalse(FREMDE_SYNTAX.matcher("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").find());
        assertFalse(FREMDE_SYNTAX.matcher("body TEXT NOT NULL, created TIMESTAMP").find());
    }

    @Test
    void dateinamenVersionenUndSyntaxAllerMigrationen() throws IOException {
        Map<String, List<String>> versionen = new LinkedHashMap<>();
        List<String> fehler = new ArrayList<>();
        int anzahl = 0;

        for (Path datei : migrationen()) {
            anzahl++;
            String name = datei.getFileName().toString();
            String kurz = datei.getParent().getParent().getParent().getParent().getParent().getParent()
                    .getFileName() + "/" + name;
            Matcher m = DATEINAME.matcher(name);
            if (!m.matches()) {
                fehler.add(kurz + " : Dateiname entspricht nicht V<nummer>__<beschreibung>.sql");
                continue;
            }
            versionen.computeIfAbsent(m.group(1), k -> new ArrayList<>()).add(kurz);
            String sql = SQL_KOMMENTAR.matcher(Files.readString(datei)).replaceAll("");
            Matcher fremd = FREMDE_SYNTAX.matcher(sql);
            if (fremd.find()) {
                fehler.add(kurz + " : keine PostgreSQL-Syntax: '" + fremd.group() + "'");
            }
        }
        versionen.forEach((version, dateien) -> {
            if (dateien.size() > 1) {
                fehler.add("Version " + version + " mehrfach: " + dateien);
            }
        });

        assertTrue(anzahl >= 1, "Positivkontrolle: keine Migration gefunden — Reactor-Wurzel nicht erkannt?");
        assertTrue(fehler.isEmpty(), () -> fehler.size() + " Befund(e):\n  " + String.join("\n  ", fehler));
    }

    /** All {@code V*.sql} below {@code <reactor>/<modul>/src/main/resources/db/migration}. */
    private static List<Path> migrationen() throws IOException {
        Path reactor = reactorWurzel();
        List<Path> dateien = new ArrayList<>();
        try (Stream<Path> module = Files.list(reactor)) {
            for (Path modul : module.filter(Files::isDirectory).sorted().toList()) {
                Path ordner = modul.resolve("src/main/resources/db/migration");
                if (!Files.isDirectory(ordner)) {
                    continue;
                }
                try (Stream<Path> sqls = Files.list(ordner)) {
                    sqls.filter(p -> p.getFileName().toString().endsWith(".sql")).sorted().forEach(dateien::add);
                }
            }
        }
        return dateien;
    }

    private static Path reactorWurzel() throws IOException {
        Path dir = Path.of(System.getProperty("user.dir")).toAbsolutePath();
        for (int i = 0; i < 8 && dir != null; i++) {
            Path pom = dir.resolve("pom.xml");
            if (Files.isRegularFile(pom) && Files.readString(pom).contains("<modules>")) {
                return dir;
            }
            dir = dir.getParent();
        }
        throw new IllegalStateException("Keine Reactor-Wurzel oberhalb von " + System.getProperty("user.dir"));
    }
}
