-- Karte 1406: Speicher-Ablagen (zuerst Nextcloud/WebDAV) unter Root -> Sidecars. Instanzweit wie sidecar,
-- App-Passwort verschluesselt (SidecarCrypto). PostgreSQL-Syntax.
CREATE TABLE IF NOT EXISTS speicher_ablage (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(40)   NOT NULL,
    art                 VARCHAR(20)   NOT NULL,
    url                 VARCHAR(500)  NOT NULL,
    benutzer            VARCHAR(200)  NOT NULL,
    passwort_encrypted  VARCHAR(2000),
    pfad                VARCHAR(500)  NOT NULL,
    ok                  BOOLEAN,
    meldung             VARCHAR(500),
    letzte_pruefung     TIMESTAMP,
    deleted             BOOLEAN       DEFAULT FALSE,
    created_by          VARCHAR(255),
    created_date        TIMESTAMP,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP,
    mandat              VARCHAR(255),
    tags                VARCHAR(5000)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_speicher_ablage_name ON speicher_ablage (name) WHERE deleted = FALSE;
