-- Karte 1400: Sidecar-Registry. Ein Eintrag je bekanntem Sidecar (aus plaintext.sidecars oder von Hand),
-- mit dem letzten Stand der Protokoll-Abfrage und dem verschluesselten Token. PostgreSQL-Syntax.
-- Instanzweit (mandat = 'system'): Sidecars sind Container des Hosts, nicht eines Mandanten, und der
-- Token muss auch ausserhalb eines Requests (Cron, Webhook) lesbar sein.
CREATE TABLE IF NOT EXISTS sidecar (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(40)   NOT NULL,
    url                 VARCHAR(500)  NOT NULL,
    quelle              VARCHAR(16)   NOT NULL,
    token_encrypted     VARCHAR(2000),
    erreichbar          BOOLEAN       NOT NULL DEFAULT FALSE,
    protokoll           VARCHAR(40),
    titel               VARCHAR(200),
    version             VARCHAR(80),
    status              VARCHAR(20),
    status_text         VARCHAR(500),
    auth_zustand        VARCHAR(20),
    antwort_ms          INTEGER,
    letzte_abfrage      TIMESTAMP,
    fehler              VARCHAR(500),
    beschreibung_json   TEXT,
    deleted             BOOLEAN       DEFAULT FALSE,
    created_by          VARCHAR(255),
    created_date        TIMESTAMP,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP,
    mandat              VARCHAR(255),
    tags                VARCHAR(5000)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sidecar_name ON sidecar (name) WHERE deleted = FALSE;
