/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
package ch.plaintext.boot.deeplink;

import java.util.List;
import java.util.Optional;

/**
 * Root service for building deep links (Card 345). Consuming modules build their mail links
 * through this service instead of assembling URLs themselves — that keeps the format in one place
 * and lets the {@code /deeplink} entry point enforce the security checks centrally.
 *
 * <p>Example from a module:
 * <pre>{@code
 * String link = deepLinkService.buildAbsoluteLink("auszahlung", auszahlung.getMandat(),
 *                                                 String.valueOf(auszahlung.getId()));
 * }</pre>
 */
public interface DeepLinkService {

    /** Path of the root entry point (without the context path). */
    String DEEPLINK_PATH = "/deeplink";

    /**
     * Absolute link for sending by mail. The base URL comes from the configuration
     * ({@code plaintext.baseurl}) — deliberately not from the current request, because links are
     * also generated by background jobs that have no request.
     *
     * @throws IllegalArgumentException if {@code type} is not registered or the tenant/id violate
     *                                  the permitted character pattern
     */
    String buildAbsoluteLink(String type, String mandat, String id);

    /** Like {@link #buildAbsoluteLink}, but relative to the context path ({@code /deeplink?...}). */
    String buildRelativeLink(String type, String mandat, String id);

    /** All registered targets, sorted by {@code type} — the basis of the root overview. */
    List<DeepLinkTarget> getTargets();

    /** The registered target for a {@code type}, or empty. Unknown types are rejected. */
    Optional<DeepLinkTarget> findTarget(String type);
}
