-- Karte 332: destructive_action_audit.id bekam KEINEN Wert -> jeder Audit-Eintrag scheiterte an
-- "null value in column id ... violates not-null constraint", was ueber die mitgerissene Transaktion
-- die eigentliche destruktive Aktion mit "Transaction silently rolled back" abbrach
-- (aufgetreten bei delete_email_account, betrifft aber JEDE Aktion mit Audit-Log in JEDER App).
--
-- Ursache: V1784705858__create_destructive_action_audit.sql legte die Spalte als
-- "id BIGINT NOT NULL PRIMARY KEY" an - ohne IDENTITY. SuperModel nutzt
-- UseExistingIdOtherwiseGenerateUsingIdentity (extends IdentityGenerator), Hibernate erwartet die ID
-- also von der Datenbank. Alle uebrigen Tabellen der Familie (impersonation_audit, api_token,
-- secret_store, oidc_config, magic_link_token, branding_logo, i18n_translation) machen es korrekt -
-- diese eine Migration war der Ausreisser.
--
-- Die Original-Migration bleibt unangetastet (Flyway-Checksum); hier wird nachtraeglich korrigiert.
-- PostgreSQL-Syntax (alle Apps dieser Familie laufen auf Postgres).
-- Idempotent: laeuft folgenlos durch, falls die Spalte bereits eine Identity besitzt.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'destructive_action_audit'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE destructive_action_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Sicherheitsnetz: falls durch frueheres ddl-auto/manuelles Nachtragen doch schon Zeilen existieren,
-- die Sequence hinter den hoechsten vergebenen Wert setzen (sonst kollidiert der naechste INSERT).
SELECT setval(pg_get_serial_sequence('destructive_action_audit', 'id'),
              COALESCE((SELECT MAX(id) FROM destructive_action_audit), 0) + 1,
              false);
