-- One-time tokens for self-service flows: e-mail verification (registration)
-- and password-reset-via-link.
--
-- Both tables intentionally model only what the flow needs:
--   - opaque, URL-safe token string (UUID-shaped, generated server-side)
--   - target identifier (e-mail / username) and mandant
--   - issued/expires timestamps
--   - consumed flag so a token can be used at most once
--
-- We deliberately do NOT carry the bcrypt hash of a future password here;
-- the password is set in the same request that consumes the token, on the
-- already-existing MyUserEntity row.
CREATE TABLE IF NOT EXISTS REGISTRATION_TOKEN (
    ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TOKEN               VARCHAR(64)  NOT NULL UNIQUE,
    EMAIL               VARCHAR(255) NOT NULL,
    MANDAT              VARCHAR(100) NOT NULL,
    ISSUED_AT           TIMESTAMP    NOT NULL,
    EXPIRES_AT          TIMESTAMP    NOT NULL,
    CONSUMED_AT         TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_REGISTRATION_TOKEN_EMAIL  ON REGISTRATION_TOKEN (EMAIL);
CREATE INDEX IF NOT EXISTS IX_REGISTRATION_TOKEN_EXPIRES ON REGISTRATION_TOKEN (EXPIRES_AT);

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKEN (
    ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TOKEN               VARCHAR(64)  NOT NULL UNIQUE,
    USERNAME            VARCHAR(255) NOT NULL,
    MANDAT              VARCHAR(100) NOT NULL,
    ISSUED_AT           TIMESTAMP    NOT NULL,
    EXPIRES_AT          TIMESTAMP    NOT NULL,
    CONSUMED_AT         TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_PWRESET_TOKEN_USERNAME ON PASSWORD_RESET_TOKEN (USERNAME);
CREATE INDEX IF NOT EXISTS IX_PWRESET_TOKEN_EXPIRES  ON PASSWORD_RESET_TOKEN (EXPIRES_AT);
