-- Karte 352: notification wurde/wurden mit "id BIGINT NOT NULL PRIMARY KEY" angelegt — ohne IDENTITY.
-- SuperModel nutzt UseExistingIdOtherwiseGenerateUsingIdentity (extends IdentityGenerator), Hibernate
-- erwartet die ID also von der Datenbank. Ohne Identity scheitert JEDER Insert an
-- "null value in column id ... violates not-null constraint" — derselbe Defekt, der bei Karte 332
-- (destructive_action_audit) die aufrufende Transaktion mitgerissen hat.
--
-- Vorbild: V1785274439__destructive_action_audit_identity.sql. Die Original-Migration bleibt
-- unangetastet (Flyway-Checksum); hier wird nachtraeglich korrigiert.
-- PostgreSQL-Syntax. Idempotent: laeuft folgenlos durch, falls die Spalte bereits Identity ist.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'notification'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Sicherheitsnetz fuer bereits vorhandene Zeilen: Sequence hinter den hoechsten Wert setzen.
SELECT setval(pg_get_serial_sequence('notification', 'id'),
              COALESCE((SELECT MAX(id) FROM notification), 0) + 1,
              false);
