-- Secrets-Management-Modul (plaintext-admin-secrets). HSQLDB-kompatible Syntax.

-- Ein verwaltetes Secret. Der WERT selbst wird NIE hier im Klartext gehalten:
-- LOCAL_DB → wert_encrypted (AES-GCM, Key aus Env PLAINTEXT_SECRET_KEY);
-- VAULTWARDEN/HASHICORP → der Wert lebt im externen Backend, hier nur Metadaten/Notiz.
CREATE TABLE IF NOT EXISTS secret_entry (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    backend_type        VARCHAR(32)  NOT NULL,          -- VAULTWARDEN | LOCAL_DB | HASHICORP
    note                VARCHAR(2000),                  -- Freitext-Notiz (User)
    wert_encrypted      VARCHAR(8000),                  -- nur LOCAL_DB: AES-GCM base64(iv||ct||tag)
    tags                VARCHAR(5000),
    deleted             BOOLEAN DEFAULT FALSE,
    mandat              VARCHAR(255),
    created_by          VARCHAR(255),
    created_date        TIMESTAMP,                      -- Zeitpunkt der Neueintragung (Audit)
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP,
    CONSTRAINT uk_secret_entry_name_mandat UNIQUE (name, mandat)
);
CREATE INDEX IF NOT EXISTS idx_secret_entry_mandat ON secret_entry (mandat);

-- Konfiguration des Secret-Backends (pro Mandant genau eine aktive Zeile). config_encrypted enthält
-- das AES-GCM-verschlüsselte Backend-Zugriffstoken/-JSON (Key = Env PLAINTEXT_SECRET_KEY).
CREATE TABLE IF NOT EXISTS secret_backend_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    backend_type        VARCHAR(32)  NOT NULL,          -- VAULTWARDEN | LOCAL_DB | HASHICORP
    config_encrypted    VARCHAR(8000),                  -- AES-GCM base64 (Token/URL/JSON)
    aktiv               BOOLEAN DEFAULT FALSE NOT NULL,
    tags                VARCHAR(5000),
    deleted             BOOLEAN DEFAULT FALSE,
    mandat              VARCHAR(255),
    created_by          VARCHAR(255),
    created_date        TIMESTAMP,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_secret_backend_config_mandat ON secret_backend_config (mandat);
